In [2]:
import os
import sys
import glob
import rasterio
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sys.path.append('../ProcessEvents/')
from config import CATCHMENT_LOOKUP_DICT, OUT_DIR # MOLLY_DIR_FF, RAINFALL_CSV_DIR, ENSEMBLE_MEMBERS, , CATCHMENTS

### Check all catchments are present

Not sure why 89 is missing - rerunning from ProcessingEvents

In [13]:
all_catchments = set(CATCHMENT_LOOKUP_DICT.keys())

catchments_with_flood_output = []
for catchment_num in all_catchments:
    catchment_name = CATCHMENT_LOOKUP_DICT[catchment_num]
    fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}.pkl"
    fp2 = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}_new.pkl"
    flood_fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/PluvialResults/5km_total/Catchment_{catchment_num}/Ens01_{catchment_num}/10cm/flooded_area_5km_total_Ens01_{catchment_num}_10cm.nc"
        
    if os.path.isfile(flood_fp) and (os.path.isfile(fp) or os.path.isfile(fp2)):
        catchments_with_flood_output.append(catchment_num)
    else:
        print(catchment_num)
        print(os.path.isfile(fp))
        print(os.path.isfile(flood_fp))

In [19]:
rainfall_events_all = []
for catchment_num in catchments_with_flood_output:
    catchment_name = CATCHMENT_LOOKUP_DICT[catchment_num]
    if catchment_num in ['33_b', '26', '89', '46']:
        fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}_new.pkl"
    else:
        fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}.pkl"
    rainfall_events = pd.read_pickle(fp)
    if 'threshold_ante_rain_1d_mean_t80' in rainfall_events.columns:
        print("Contains antecedent rainfall variables", catchment_num)
        rainfall_events.drop(['threshold_ante_rain_1d_mean_t80', 'cluster_ante_rain_1d_mean_t80',
       'threshold_ante_rain_2d_mean_t80', 'cluster_ante_rain_2d_mean_t80',
       'threshold_ante_rain_5d_mean_t80', 'cluster_ante_rain_5d_mean_t80',
       'threshold_ante_rain_10d_mean_t80', 'cluster_ante_rain_10d_mean_t80',
       'threshold_ante_sm_mean_t80', 'cluster_ante_sm_mean_t80',
                                   'threshold_ante_rain_1d_mean_t60', 'cluster_ante_rain_1d_mean_t60',
       'threshold_ante_rain_2d_mean_t60', 'cluster_ante_rain_2d_mean_t60',
       'threshold_ante_rain_5d_mean_t60', 'cluster_ante_rain_5d_mean_t60',
       'threshold_ante_rain_10d_mean_t60', 'cluster_ante_rain_10d_mean_t60',
                                   'threshold_ante_rain_2d_mean_t50', 'cluster_ante_rain_2d_mean_t50',
       'threshold_ante_rain_5d_mean_t50', 'cluster_ante_rain_5d_mean_t50',
       'threshold_ante_rain_10d_mean_t50', 'cluster_ante_rain_10d_mean_t50',
                            'neighbourhood_ante_rain_2d_mean', 'neighbourhood_ante_rain_2d_point',
       'neighbourhood_ante_rain_5d_mean', 'neighbourhood_ante_rain_5d_point',
       'neighbourhood_ante_rain_10d_mean', 'neighbourhood_ante_rain_10d_point',
                     'threshold_ante_sm_mean_t60', 'cluster_ante_sm_mean_t60',
                            'threshold_ante_rain_1d_mean_t50', 'cluster_ante_rain_1d_mean_t50',
       'threshold_ante_sm_mean_t50', 'cluster_ante_sm_mean_t50',      'neighbourhood_ante_rain_1d_mean', 'neighbourhood_ante_rain_1d_point',
       'neighbourhood_ante_sm_mean', 'neighbourhood_ante_sm_point',], axis=1, inplace=True)
    if 'start_month' in rainfall_events.columns:
        print("contains start_month", catchment_num)
        del rainfall_events['start_day']
        del rainfall_events['start_hour']
        rainfall_events.rename(columns={'start_month': 'month'}, inplace=True)
        rainfall_events.rename(columns={'start_year':'start_year'}, inplace=True)
    rainfall_events['catchment_num'] = catchment_num
    # print(f"Catchment {catchment_num} has {len(rainfall_events)}, of which {len(rainfall_events) - len(rainfall_events_complete)} are mismatched")
    rainfall_events_all.append(rainfall_events) 
rainfall_events_all_df = pd.concat(rainfall_events_all, ignore_index=True)   
rainfall_events_all_df = rainfall_events_all_df[rainfall_events_all_df['max_precip']<130].copy()

contains start_month 105
Contains antecedent rainfall variables 33_b
contains start_month 33_b
Contains antecedent rainfall variables 23
contains start_month 23
Contains antecedent rainfall variables 89
contains start_month 89
contains start_month 40
Contains antecedent rainfall variables 26
contains start_month 26
Contains antecedent rainfall variables 46
contains start_month 46

### Save to pickle file 
Can't save to csv as this cuts off some of the data

In [20]:
rainfall_events_all_df.to_pickle("/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/all_catchments.pkl")

In [22]:
catchment_num = '46'
catchment_name = CATCHMENT_LOOKUP_DICT[catchment_num]
fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}_new.pkl"
rainfall_events = pd.read_pickle(fp)
fp = f"/scratch/hydro4/users/kv25483/FutureFlood/Data/EventDetails/Catchment_{catchment_num}/{catchment_name}.pkl"
rainfall_events2 = pd.read_pickle(fp)

In [24]:
rainfall_events2

,max_precip,t_global,t_local,x_idx,y_idx,x_idx_global,y_idx_global,x_coord,y_coord,ens,...,cluster_rain_total_t80,cluster_n_cells_t80,threshold_flood_10_area_t80,cluster_flood_10_area_t80,threshold_flood_10_vol_t80,cluster_flood_10_vol_t80,threshold_flood_30_area_t80,cluster_flood_30_area_t80,threshold_flood_30_vol_t80,cluster_flood_30_vol_t80
0,32.496731,5413,6,2,4,93,18,267500.0,57500.0,01,...,59.062752,2,0.3735,0.3735,156575.703125,156575.703125,0.0990,0.0990,94197.601562,94197.601562
1,40.201675,7556,16,0,8,91,22,257500.0,77500.0,01,...,40.201675,1,0.9990,0.3474,306254.687500,97033.500000,0.2070,0.0738,126680.398438,38114.101562
2,40.591404,7383,9,2,7,93,21,267500.0,72500.0,01,...,40.591404,1,0.2808,0.2808,69543.898438,69543.898438,0.0198,0.0198,15972.299805,15972.299805
3,66.453850,4572,3,1,6,92,20,262500.0,67500.0,01,...,66.453850,1,0.5067,0.5067,140122.796875,140122.796875,0.0801,0.0801,50616.000000,50616.000000
4,35.003792,6042,5,1,9,92,23,262500.0,82500.0,01,...,35.003792,1,0.4734,0.4734,151416.000000,151416.000000,0.0648,0.0648,51214.500000,51214.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1393,33.033485,7801,14,5,4,96,18,282500.0,57500.0,15,...,33.033485,1,1.8225,0.3816,901363.500000,200346.296875,0.5805,0.1143,574803.875000,132460.203125
1394,30.487280,4259,2,1,10,92,24,262500.0,87500.0,15,...,30.487280,1,0.2214,0.2214,80321.398438,80321.398438,0.0324,0.0324,43460.101562,43460.101562
1395,36.359234,7004,9,2,9,93,23,267500.0,82500.0,15,...,36.359234,1,1.0188,0.5670,294776.125000,166829.406250,0.1485,0.0927,92521.796875,59292.898438
1396,71.383133,6132,3,1,2,92,16,262500.0,47500.0,15,...,71.383133,1,0.6912,0.6912,312277.500000,312277.500000,0.2826,0.2826,218386.796875,218386.796875
1397,30.938654,6717,16,1,6,92,20,262500.0,67500.0,15,...,56.161867,2,0.3573,0.3573,111744.000000,111744.000000,0.0288,0.0288,33634.800781,33634.800781

In [23]:
rainfall_events

,max_precip,t_global,t_local,x_idx,y_idx,x_idx_global,y_idx_global,x_coord,y_coord,ens,...,threshold_ante_rain_1d_mean_t80,cluster_ante_rain_1d_mean_t80,threshold_ante_rain_2d_mean_t80,cluster_ante_rain_2d_mean_t80,threshold_ante_rain_5d_mean_t80,cluster_ante_rain_5d_mean_t80,threshold_ante_rain_10d_mean_t80,cluster_ante_rain_10d_mean_t80,threshold_ante_sm_mean_t80,cluster_ante_sm_mean_t80
0,32.496731,5413,6,2,4,93,18,267500.0,57500.0,01,...,3.507196,3.507196,4.764557,4.764557,4.764606,4.764606,4.764606,4.764606,59.978121,59.978121
1,40.201675,7556,16,0,8,91,22,257500.0,77500.0,01,...,0.061329,0.031721,0.386087,0.056019,22.577217,18.502541,116.036484,102.352524,72.350859,81.510284
2,40.591404,7383,9,2,7,93,21,267500.0,72500.0,01,...,3.855359,3.855359,4.700033,4.700033,6.351168,6.351168,28.923334,28.923334,66.451996,66.451996
3,66.453850,4572,3,1,6,92,20,262500.0,67500.0,01,...,3.128356,3.128356,15.258251,15.258251,15.258251,15.258251,109.720947,109.720947,73.865456,73.865456
4,35.003792,6042,5,1,9,92,23,262500.0,82500.0,01,...,0.073017,0.073017,0.097548,0.097548,1.832884,1.832884,13.772414,13.772414,44.521973,44.521973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1393,33.033485,7801,14,5,4,96,18,282500.0,57500.0,15,...,0.131198,0.145702,0.131198,0.145702,23.091454,22.637955,52.956955,55.768566,62.338991,65.031677
1394,30.487280,4259,2,1,10,92,24,262500.0,87500.0,15,...,36.009384,36.009384,42.731220,42.731220,44.821903,44.821903,44.834293,44.834293,46.043941,46.043941
1395,36.359234,7004,9,2,9,93,23,267500.0,82500.0,15,...,2.356436,2.116510,2.453525,2.131792,6.088469,5.229211,7.330350,6.218989,39.091511,37.228207
1396,71.383133,6132,3,1,2,92,16,262500.0,47500.0,15,...,0.000012,0.000012,4.556618,4.556618,4.591834,4.591834,5.969335,5.969335,45.830574,45.830574
1397,30.938654,6717,16,1,6,92,20,262500.0,67500.0,15,...,0.760919,0.760919,0.778319,0.778319,0.778484,0.778484,37.052361,37.052361,52.417702,52.417702